### PR TITLE
32bit support

### LINKED ISSUE #175: 32 bit support fails
Sparrow seems to hard-code that the underlying archiotecture is 64bit, see `build.log` in https://koji.fedoraproject.org/koji/taskinfo?taskID=121660160

### PR DESCRIPTION
**Pull request by Klaim**
- [ ] CI builds and tests 32bit flavor of the current configurations (assuming all host platforms are 64bit)
  - [x] Windows builds
  - [ ] Linux builds
  - [ ] MacOS builds
- [x] fix #175 :
  - support 32bit-only sizes
  - provides a way for user to specify if they want to enable 64bit sizes on 64bit target platforms, or if they want to restrict all sizes under 32bit, whatever the platform;
  - provides a way for user to enable/disable runtime checks on the size values that must be under 32bit.
 - [ ] tests for conversion functions

### CODE REVIEW

**Comment by Klaim** [comment]
For info: the ci runs that use vcpkg are currently affected by  https://github.com/microsoft/vcpkg/issues/41199

**Comment by Klaim** [comment]
Status update:
- tests are incoming (had to handle something else first)
- CI is affected by vcpkg's bug which is fixed but the fix will come in the next windows image (not yet)
- the linux and macos 32bit ci checks will be added in another PR

**Comment by DerThorsten** [comment]
I believe we should stop working on this until things are more stable.
This is already more or less unmergable

**Review by DerThorsten — CHANGES_REQUESTED** [review]
this is so outdated, this cannot be merged with reasonable amount of work.

**Comment by JohanMabille** [comment]
Most of the conflicts in this PR come from the merge of #225 that remove old layouts and related stuff, on which this PR was started. Porting the changes to the new arrays is not that much work, and solving the conflicts will be mostly dropping the changes from files that have been deleted.

**Comment by DerThorsten** [comment]
Sorry if my previous comments sounded a bit rude. I am just always a bit alarmed when I see many files in conflict ;)

**Pull request closed without merging**
